[package]
name = "avro-util"
version = "0.1.0"
authors = ["jeffrade <jrade@cars.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
